package org.transporteaereo.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-16T01:28:30.249-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "TransporteAereoService",
                  wsdlLocation = "file:/D:/oxygen/eclipse-workspace/transporteAereoSOAPService/src/main/resources/wsdl/transporteaereo.wsdl",
                  targetNamespace = "http://www.transporteaereo.org/demo/")
public class TransporteAereoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.transporteaereo.org/demo/", "TransporteAereoService");
    public final static QName TransporteAereoServicesEndpoint = new QName("http://www.transporteaereo.org/demo/", "TransporteAereoServicesEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/oxygen/eclipse-workspace/transporteAereoSOAPService/src/main/resources/wsdl/transporteaereo.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransporteAereoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/oxygen/eclipse-workspace/transporteAereoSOAPService/src/main/resources/wsdl/transporteaereo.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransporteAereoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransporteAereoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransporteAereoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TransporteAereoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TransporteAereoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TransporteAereoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TransporteAereoSystemServices
     */
    @WebEndpoint(name = "TransporteAereoServicesEndpoint")
    public TransporteAereoSystemServices getTransporteAereoServicesEndpoint() {
        return super.getPort(TransporteAereoServicesEndpoint, TransporteAereoSystemServices.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransporteAereoSystemServices
     */
    @WebEndpoint(name = "TransporteAereoServicesEndpoint")
    public TransporteAereoSystemServices getTransporteAereoServicesEndpoint(WebServiceFeature... features) {
        return super.getPort(TransporteAereoServicesEndpoint, TransporteAereoSystemServices.class, features);
    }

}
