package co.com.aviancademo.aviancademo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-15T11:00:40.516-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://aviancaDemo.aviancademo.com.co/", name = "Avianca")
@XmlSeeAlso({ObjectFactory.class})
public interface Avianca {

    @WebMethod(operationName = "ConsultarReserva", action = "consultarReserva")
    @Action(input = "consultarReserva", output = "http://aviancaDemo.aviancademo.com.co/Avianca/ConsultarReservaResponse")
    @RequestWrapper(localName = "ConsultarReserva", targetNamespace = "http://aviancaDemo.aviancademo.com.co/", className = "co.com.aviancademo.aviancademo.ConsultarReserva")
    @ResponseWrapper(localName = "ConsultarReservaResponse", targetNamespace = "http://aviancaDemo.aviancademo.com.co/", className = "co.com.aviancademo.aviancademo.ConsultarReservaResponse")
    @WebResult(name = "Reserva", targetNamespace = "")
    public co.com.aviancademo.aviancademo.Reserva consultarReserva(
        @WebParam(name = "IdReserva", targetNamespace = "")
        java.lang.String idReserva
    );

    @WebMethod(operationName = "RealizarReserva", action = "realizarReserva")
    @Action(input = "realizarReserva", output = "http://aviancaDemo.aviancademo.com.co/Avianca/RealizarReservaResponse")
    @RequestWrapper(localName = "RealizarReserva", targetNamespace = "http://aviancaDemo.aviancademo.com.co/", className = "co.com.aviancademo.aviancademo.RealizarReserva")
    @ResponseWrapper(localName = "RealizarReservaResponse", targetNamespace = "http://aviancaDemo.aviancademo.com.co/", className = "co.com.aviancademo.aviancademo.RealizarReservaResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public co.com.aviancademo.aviancademo.Response realizarReserva(
        @WebParam(name = "Reserva", targetNamespace = "")
        co.com.aviancademo.aviancademo.Reserva reserva
    );

    @WebMethod(operationName = "CancelarReserva", action = "cancelarReserva")
    @Action(input = "cancelarReserva", output = "http://aviancaDemo.aviancademo.com.co/Avianca/CancelarReservaResponse")
    @RequestWrapper(localName = "CancelarReserva", targetNamespace = "http://aviancaDemo.aviancademo.com.co/", className = "co.com.aviancademo.aviancademo.CancelarReserva")
    @ResponseWrapper(localName = "CancelarReservaResponse", targetNamespace = "http://aviancaDemo.aviancademo.com.co/", className = "co.com.aviancademo.aviancademo.CancelarReservaResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public co.com.aviancademo.aviancademo.Response cancelarReserva(
        @WebParam(name = "IdReserva", targetNamespace = "")
        java.lang.String idReserva
    );
}
