package co.com.aviancademo.aviancademo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-15T11:00:40.544-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "ServicioWebService",
                  wsdlLocation = "file:/src/main/resources/wsdlexterno/AviancaSOAP.wsdl",
                  targetNamespace = "http://aviancaDemo.aviancademo.com.co/")
public class ServicioWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://aviancaDemo.aviancademo.com.co/", "ServicioWebService");
    public final static QName AviancaPort = new QName("http://aviancaDemo.aviancademo.com.co/", "AviancaPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/src/main/resources/wsdlexterno/AviancaSOAP.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioWebService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/src/main/resources/wsdlexterno/AviancaSOAP.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServicioWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicioWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicioWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Avianca
     */
    @WebEndpoint(name = "AviancaPort")
    public Avianca getAviancaPort() {
        return super.getPort(AviancaPort, Avianca.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Avianca
     */
    @WebEndpoint(name = "AviancaPort")
    public Avianca getAviancaPort(WebServiceFeature... features) {
        return super.getPort(AviancaPort, Avianca.class, features);
    }

}
