package org.avianca.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-16T00:30:23.544-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "AviancaService",
                  wsdlLocation = "file:/D:/oxygen/eclipse-workspace/transporteAereoSOAPService/src/main/resources/wsdl/transporteaereo.wsdl",
                  targetNamespace = "http://www.avianca.org/demo/")
public class AviancaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.avianca.org/demo/", "AviancaService");
    public final static QName AviancaServicesEndpoint = new QName("http://www.avianca.org/demo/", "AviancaServicesEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/oxygen/eclipse-workspace/transporteAereoSOAPService/src/main/resources/wsdl/transporteaereo.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AviancaService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/oxygen/eclipse-workspace/transporteAereoSOAPService/src/main/resources/wsdl/transporteaereo.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AviancaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AviancaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AviancaService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AviancaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AviancaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AviancaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AviancaSystemServices
     */
    @WebEndpoint(name = "AviancaServicesEndpoint")
    public AviancaSystemServices getAviancaServicesEndpoint() {
        return super.getPort(AviancaServicesEndpoint, AviancaSystemServices.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AviancaSystemServices
     */
    @WebEndpoint(name = "AviancaServicesEndpoint")
    public AviancaSystemServices getAviancaServicesEndpoint(WebServiceFeature... features) {
        return super.getPort(AviancaServicesEndpoint, AviancaSystemServices.class, features);
    }

}
