package com.iamericanairlines.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-15T12:08:05.301-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://services.IAmericanAirlines.com/", name = "IAmericanAirlines")
@XmlSeeAlso({ObjectFactory.class})
public interface IAmericanAirlines {

    @WebMethod(operationName = "RealizarReserva", action = "realizarReserva")
    @Action(input = "realizarReserva", output = "http://services.IAmericanAirlines.com/IAmericanAirlines/RealizarReservaResponse")
    @RequestWrapper(localName = "RealizarReserva", targetNamespace = "http://services.IAmericanAirlines.com/", className = "com.iamericanairlines.services.RealizarReserva")
    @ResponseWrapper(localName = "RealizarReservaResponse", targetNamespace = "http://services.IAmericanAirlines.com/", className = "com.iamericanairlines.services.RealizarReservaResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public com.iamericanairlines.services.Response realizarReserva(
        @WebParam(name = "Reserva", targetNamespace = "")
        com.iamericanairlines.services.Reserva reserva
    );

    @WebMethod(operationName = "ConsultarReserva", action = "consultarReserva")
    @Action(input = "consultarReserva", output = "http://services.IAmericanAirlines.com/IAmericanAirlines/ConsultarReservaResponse")
    @RequestWrapper(localName = "ConsultarReserva", targetNamespace = "http://services.IAmericanAirlines.com/", className = "com.iamericanairlines.services.ConsultarReserva")
    @ResponseWrapper(localName = "ConsultarReservaResponse", targetNamespace = "http://services.IAmericanAirlines.com/", className = "com.iamericanairlines.services.ConsultarReservaResponse")
    @WebResult(name = "Reserva", targetNamespace = "")
    public com.iamericanairlines.services.Reserva consultarReserva(
        @WebParam(name = "IdReserva", targetNamespace = "")
        java.lang.String idReserva
    );

    @WebMethod(operationName = "CancelarReserva", action = "cancelarReserva")
    @Action(input = "cancelarReserva", output = "http://services.IAmericanAirlines.com/IAmericanAirlines/CancelarReservaResponse")
    @RequestWrapper(localName = "CancelarReserva", targetNamespace = "http://services.IAmericanAirlines.com/", className = "com.iamericanairlines.services.CancelarReserva")
    @ResponseWrapper(localName = "CancelarReservaResponse", targetNamespace = "http://services.IAmericanAirlines.com/", className = "com.iamericanairlines.services.CancelarReservaResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public com.iamericanairlines.services.Response cancelarReserva(
        @WebParam(name = "IdReserva", targetNamespace = "")
        java.lang.String idReserva
    );
}
